### ISSUE TITLE
New API endpoint 

### ISSUE THREAD

**Issue by PacaHat** [itzzzme/anime-api#10]
The new API endpoint for streaming links is confusing. The example you provided for Frieren works,

https://zen-api-brown.vercel.app/api/stream?id=frieren-beyond-journeys-end-18542?ep=107257&server=hd-1&type=sub

But it only shows the subbed version, as the type is set to "sub." However, when I change the type to "dub," no link is displayed. Additionally, when I try the endpoint with a different anime episode ID, I encounter the same problem.

https://zen-api-brown.vercel.app/api/stream?id=bleach-806?ep=13793&server=hd-1&type=sub

What did I do wrong..?

**Comment by PacaHat** [comment]
Thank you for clarifying! I’ll wait for the upcoming updates.

**Comment by itzzzme** [comment]
> Thank you for clarifying! I’ll wait for the upcoming updates.

@PacaHat it's fixed now
