### ISSUE TITLE
Api response null

### ISSUE THREAD

**Issue by PacaHat** [itzzzme/anime-api#12]
Since yesterday, this error has been popping up now and then. 
![image](https://github.com/user-attachments/assets/c1169cce-dcf9-4ef3-b295-29ce6c950170)

{
  "success": true,
  "results": []
}

**Comment by itzzzme** [comment]
![image](https://github.com/user-attachments/assets/3f76ad27-88e3-4f02-a30d-3e9a4d063048)

It's giving the response just fine. Can you check your vercel log what's causing the error?
