### ISSUE TITLE
Can I work on your documentation?

### ISSUE THREAD

**Issue by sunkanmii** [itzzzme/anime-api#2]
Hey! 👋🏾

I'm Sunkanmi and I'm a Technical Writer looking to contribute to API documentation on Github. I want to know if I can submit a PR for a Swagger documentation for this API and help refine your Github readme as well.

Let me know if I can get started on this. :)

Hope to speak with you soon!

**Comment by itzzzme** [comment]
well I am not quiet familiar with swagger but if you want to update the github readme you are welcome as long as it follows the API's returned data structure
