### ISSUE TITLE
Endpoint not working

### ISSUE THREAD

**Issue by LUMINARSFT** [itzzzme/anime-api#4]
Hello im glad you developed this powerfull api and I appreciate it very much.
However since few days i noticed that below problems with api.
_(I deployed on vercel)_

### 1. GET /api/stream 

The api returns all info as expected. but in sources i cant recognise any playable links(m3u8 or whatever) instead it shows some value only in it
Reproduce url : `/api/stream?id=frieren-beyond-journeys-end-18542?ep=107257`
Example : `"sources": "U2FsdGVkX183o8n8KsgN0xNwO+EpZaoqO0ksYJkVyfxRa2DCzNUfilyaGgMMp0A2LGLqHY8obSxmRcyrFLvZlHvLELhQoU/XHWq5OAC2RmxDrQy7PM/7nhwNZjgh9GBBSpDddsYfq6Ek08VaBE630nq0vBaVhXokDJkuY25ZW3+2vTOZOePreLJ8bBISS8RrymnVmQNrFbs+TnZmqFZardt/lm/TywR94kH3cXH3HWWzuIotqXwZIDEq1vHrKFTS7CK7/V0zPKKPmKxlHFGjrViTnLI0PFmFpR9ak+ITrln2HgQq8sSldDS6U1uVM16feK8n07yTHCZEAgzQ9ei92DehndpFNxs9wyjUDxFXj4G0Us3lkwu+pfrh1hEJLRzzOf9pkszHLOS5RSJO85jhSJ1ffE4P6KRp6zzEoMa4DcfPeCkGiAz0a0wVBk662f0gApZ9BslETbX85oHezm+ztJSgdkM6+XOiXvMi+GTo9Aw==",`

### 2.GET /api/servers/ endpoint not working
This endpoint doesnt work and returns error 404
Reproduce url :` /api/servers/demon-slayer-kimetsu-no-yaiba-hashira-training-arc-19107?ep=124260`

**And if you confortable with fixing these issues it would be very helpfull**
Thank you

**Comment by LUMINARSFT** [comment]
Well i tried deleting and redeploying me vercel project and gthub fork too. Now wven home pages isnt loading its says "Serverless function crashed"

The commin logs in vercel like below.
```
TypeError: Cannot read properties of undefined (reading 'split')
    at file:///var/task/api/server.js:18:52
    at ModuleJob.run (node:internal/modules/esm/module_job:234:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:473:24)
    at async d (/opt/rust/nodejs.js:8:18858)
Node.js process exited with exit status: 1. The logs above can help with debugging the issue.
```

Im feeling really bad bothering you with this problem. But i have no idea why this happen. Accoriding to my knowledge is has problem with scraping the web(maybe).

**Comment by itzzzme** [comment]
can you send me a video what problem you are facing from forking to post deployment

**Comment by anime-kun32** [comment]
the same error i have as well

**Comment by itzzzme** [comment]
Try to refork the project and redeploy it on vercel

**Comment by anime-kun32** [comment]
tried that already even created another accoutn fokred the project and then deployed the same error , i then tried runnning it on node js i got server crassh waiting for command

**Comment by itzzzme** [comment]
@LUMINARSFT check it out now it should be fixed just refork the repo and redeploy it
