### ISSUE TITLE
Deployment crashed 

### ISSUE THREAD

**Issue by anime-kun32** [itzzzme/anime-api#5]
![image](https://github.com/user-attachments/assets/1c5e0fbb-833c-4097-b882-972c55aabfd6)
 i get this error when deploying on vercel

**Comment by anime-kun32** [comment]
ok

**Comment by itzzzme** [comment]
not the build logs but the live logs you get in vercel like this

![Screenshot 2024-11-19 204545-mh](https://github.com/user-attachments/assets/7ae057b1-3052-4138-a1b4-0554445a8f93)
![Screenshot 2024-11-19 204545-mh (1)](https://github.com/user-attachments/assets/f92b9875-2cee-4643-aa88-0723f9ac3e80)

you can click on each logs to view what error is happening

**Comment by anime-kun32** [comment]
[logs_result (1).json](https://github.com/user-attachments/files/17831009/logs_result.1.json)

**Comment by itzzzme** [comment]
Okay. So to fix the issue refer to the .env.example file though I have fixed the error in current release so even if you don't add .env it won't throw error but to use your api in frontend I will suggest to add

`ALLOWED_ORIGINS` as described in `.env.example` file
