### ISSUE TITLE
hls links only point to two videos

### ISSUE THREAD

**Issue by tobeski03** [itzzzme/anime-api#6]
all streaming links only point to two videos. no matter what video I QUERY

**Comment by itzzzme** [comment]
I couldn't understand your problem can you ellaborate with a video or image

**Comment by tobeski03** [comment]
https://github.com/user-attachments/assets/81b36800-f114-411b-ac22-273288fb25ef

As you can see. the streaming links only points to 2 videos and all apis were pointed accurately. I used the "/api/stream?id=road-of-naruto-18220" for example and it points to the same video

**Comment by tobeski03** [comment]
Perhaps there is something 

> issue.mp4 
> As you can see. the streaming links only points to 2 videos and all apis were pointed accurately. I used the "/api/stream?id=road-of-naruto-18220" for example and it points to the same video

Perhaps there is something I am not doing properly?

**Comment by itzzzme** [comment]
> Perhaps there is something 
> 
> > issue.mp4 
> > As you can see. the streaming links only points to 2 videos and all apis were pointed accurately. I used the "/api/stream?id=road-of-naruto-18220" for example and it points to the same video
> 
> Perhaps there is something I am not doing properly?

As you stated in the API endpoint you have to provide the ep parameter as I have shown in the documentation of the API. refer the readme.md so if you have the API endpoint like

/api/stream?id=road-of-naruto-18220

There will also be an ep query parameter like this

/api/stream?id=road-of-naruto-18220?ep=<ep_id>

**Comment by tobeski03** [comment]
this is exactly what I am doing and I still get same videos from the streaming links

**Comment by tobeski03** [comment]
please help test it also from your end

**Comment by itzzzme** [comment]
> please help test it also from your end

Send me the response you are getting with the corresponding request. It will elaborate the problem and also will make it clear to test the endpoint
