### ISSUE TITLE
Streaming links error

### ISSUE THREAD

**Issue by PacaHat** [itzzzme/anime-api#8]
Streaming api response aren't showing any streaming link

{
"success": true,
"results": {
"streamingLink": [
{
"id": "578153",
"type": "dub",
"link": [],
"tracks": [],
"server": "HD-1"
},
{
"id": "52961",
"type": "dub",
"link": [],
"tracks": [],
"server": "HD-2"
},

**Comment by itzzzme** [comment]
> Streaming api response aren't showing any streaming link
> 
> {
> "success": true,
> "results": {
> "streamingLink": [
> {
> "id": "578153",
> "type": "dub",
> "link": [],
> "tracks": [],
> "server": "HD-1"
> },
> {
> "id": "52961",
> "type": "dub",
> "link": [],
> "tracks": [],
> "server": "HD-2"
> },

I will fix it very soon. Thanks for mentioning the issue

**Comment by iamrizwancom** [comment]
same problem here, waiting for update

**Comment by iamrizwancom** [comment]
bro i want to contact you, can you share your contact number, i have a paid project

**Comment by itzzzme** [comment]
@iamrizwancom  you can contact me on discord. My username is `itzzzm3`

**Comment by PacaHat** [comment]
> @iamrizwancom you can contact me on discord. My username is `itzzzm3`

Any progress..?

**Comment by itzzzme** [comment]
> > @iamrizwancom you can contact me on discord. My username is `itzzzm3`
> 
> Any progress..?

It's in progress. I have just resumed the proejct

**Comment by itzzzme** [comment]
The streaming link issue is fixed now
