### ISSUE TITLE
qtip info

### ISSUE THREAD

**Issue by PacaHat** [itzzzme/anime-api#9]
qtip info endpoint not working 

https://zen-api-brown.vercel.app/api/qtip/806

{
  "success": true,
  "results": {
    "title": "",
    "rating": "",
    "quality": "",
    "subCount": "",
    "dubCount": "",
    "episodeCount": "",
    "type": "",
    "description": "",
    "japaneseTitle": "",
    "Synonyms": "",
    "airedDate": "",
    "status": "",
    "genres": []
  }
}

![image](https://github.com/user-attachments/assets/1ae0fb0d-c1ca-4a03-9842-bc3996d41488)

**Comment by itzzzme** [comment]
Thanks for pointing the issue. It's fixed now
